### ISSUE TITLE
Regexp should replace any existing seeds seeting in cassandra.yaml. Not just 127.0.0.1

### ISSUE THREAD

**Issue by razvvan** [LukeTillman/dse-docker#15]
Currently, the sed matches and replaces the seeds configuration only on the first run when the seeds is set to 127.0.0.1.

Considering the use case for this image is development, it is very likely that the container will not always be allocated the same ip. If the seeds ip is not correct, gossip will fail and cassandra will shutdown.  

Proposed solution: #14

**Comment by LukeTillman** [comment]
PR merged and should be released in the 5.1.1 image.
