### ISSUE TITLE
dsefs directory creation failed during start up 

### ISSUE THREAD

**Issue by norim** [LukeTillman/dse-docker#18]
Hi Luke,

the directory /var/lib/dsefs needs to be added in the Dockerfile for the versions DSE5.1 and DSE5.1.1
dsefs server cant start and therefor dse spark and spark-sql not working properly. 

During startup I can see an exception notifying that dsefs directory cant be created. Permission denied. dse is trying to create it during startup under /var/lib/

-nm

**Comment by LukeTillman** [comment]
Good catch! I'm not going to fix it in `5.1.0`, but I will try and push a new image up to Docker Hub for `5.1.1`. Thanks for the report.
