### ISSUE TITLE
How to run Graph properly?

### ISSUE THREAD

**Issue by schrepfler** [LukeTillman/dse-docker#2]
I've noticed that when I start dse with Graph enabled (ex. by adding -k -g -s) I still can't connect to it via the DataStax Studio. Ex. I'm getting "All DSE gremlin server hosts are currently down or don't have the 'graph' workload set. Please, make sure that hosts are available and have the 'graph' workload and retry." I've exposed all ports to the host, connecting to 127.0.0.1:9042 and the "DSE Graph QuickStart" notebook.

I've noticed that the under /opt/dse/resources/dse/conf/dse.yaml
``` 
graph:
  schema_mode: Production
```
can this be related? Should I somehow replace this config file?

**Comment by LukeTillman** [comment]
Hey @schrepfler, were you able to figure it out? I haven't attempted to run graph with this Docker image (yet). If you did get it running, did you have to change something with this Docker image or was it some other setup/configuration option that needed to change?

**Comment by schrepfler** [comment]
Not yet, I've abandoned it for the heavy VM in the hope you will get to it first (I don't use either DSE or Docker day to day so chose to focus on the DSE part.)

**Comment by LukeTillman** [comment]
So I finally got a chance to try this out. If you want to do it with Studio + DSE all running in Docker with Docker Compose, I have a sample `docker-compose.yml` file available here:

https://github.com/LukeTillman/ds-studio-docker/blob/master/examples/docker-compose.yml

I also wrote a blog post about the (way more complicated than it should have been) experience:

http://www.luketillman.com/datastax-graph-and-studio-with-docker-compose/

Good luck!

**Comment by schrepfler** [comment]
I'll give it a go. Thanks!

**Comment by schrepfler** [comment]
Tested, works great.
