### ISSUE TITLE
Reference blog article on how to expose services to host

### ISSUE THREAD

**Issue by schrepfler** [LukeTillman/dse-docker#31]
It would be good to both document binding services to host and reference your [blog article](http://www.luketillman.com/datastax-graph-and-studio-with-docker-compose/) on how to expose dse-docker services to host in the README.md.

**Comment by LukeTillman** [comment]
Closing this to archive this repository. Check out the new [official Docker images from DataStax](https://github.com/datastax/docker-images). Thanks!
