### ISSUE TITLE
How do I run this with analytics turned on?

### ISSUE THREAD

**Issue by wildengineer** [LukeTillman/dse-docker#5]
I am trying to figure out how to turn analytics on. It seems like only cassandra is turned on by default. What am I missing?

**Comment by LukeTillman** [comment]
The [`DESCRIPTION.md`][starting-dse] has a section on how to start it. It's got a link in that section to the documentation for the [command line flags][dse-start-docs] available if you don't want to use the default (which is to just start a Cassandra node). So, put it all together and you should be able to start a Spark node by adding the `-k` switch like this:

```
docker run --name my-dse -d luketillman/datastax-enterprise:5.0.4 -k
```

If you need to expose any of the ports to your host, you'll want to be sure to add the `-p xxxx:yyyy` or `-P` flags after the `-d`. You can find a list of the [ports used by DSE][dse-ports] in the docs. So, for example, to expose the CQL port (9042) as port 9042 on the host, you'd do:

```
docker run --name my-dse -d -p 9042:9042 luketillman/datastax-enterprise:5.0.4 -k
```

See the [docker run][docker-run] docs for more info.

HTH.

[starting-dse]: https://github.com/LukeTillman/dse-docker/blob/master/DESCRIPTION.md#starting-dse
[dse-start-docs]: http://docs.datastax.com/en/datastax_enterprise/4.8/datastax_enterprise/startStop/refDseStandalone.html
[dse-ports]: http://docs.datastax.com/en/latest-dse/datastax_enterprise/sec/configFirewallPorts.html
[docker-run]: https://docs.docker.com/engine/reference/run/

**Comment by wildengineer** [comment]
Thanks Luke!
