### ISSUE TITLE
Create a healthcheck?

### ISSUE THREAD

**Issue by BlueHotDog** [LukeTillman/dse-docker#9]
Hey, Docker now supports health-checks, which are extremely useful for DSE.
Any thoughts before i implement them?

**Comment by LukeTillman** [comment]
Great idea. As for what to use for a health check command, maybe just testing that `cqlsh` can connect and run a simple command on a system table? Something like:

```
cqlsh --execute="SELECT * FROM system.local"
```

But I'm open to ideas if you have them. Feel free to send a PR.

**Comment by BlueHotDog** [comment]
https://github.com/LukeTillman/dse-docker/pull/11
very initial PR to get the discussion going

**Comment by casassg** [comment]
Idea for this: https://github.com/kubernetes/kubernetes/blob/master/examples/storage/cassandra/image/files/ready-probe.sh

It's from kubernetes example cassandra docker image.

**Comment by LukeTillman** [comment]
Closing this to archive this repository. Check out the new [official Docker images from DataStax](https://github.com/datastax/docker-images). Thanks!
